# Generated by Django 6.0.7 on 2026-07-19 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_lifecycle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresult',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='academicresult',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='enrollmentplan',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='enrollmentplan',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='academic_lifecycle_studentprofile_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='academic_lifecycle_studentprofile_effective_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='academic_lifecycle_taskinstance_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='academic_lifecycle_taskinstance_effective_period_valid'),
        ),
    ]
