# Generated by Django 5.2.16 on 2026-07-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_lifecycle', '0002_academicresult_created_by_actor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='rule_package_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='academicstatus',
            name='status',
            field=models.CharField(choices=[('candidate', 'Calon'), ('admitted', 'Diterima'), ('active', 'Aktif'), ('absent', 'Mangkir'), ('leave', 'Cuti'), ('suspended', 'Skorsing'), ('transfer', 'Pindah'), ('dropout', 'Putus Studi'), ('graduated', 'Lulus'), ('withdrawn', 'Mengundurkan Diri'), ('deceased', 'Wafat')], max_length=24),
        ),
    ]
