# Generated by Django 5.2.16 on 2026-07-19 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_lifecycle', '0003_studentprofile_rule_package_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(max_length=120, unique=True)),
                ('schema_version', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='academic_lifecycle_lifecycleconfiguration_version_gte_1'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='academic_lifecycle_lifecycleconfiguration_effective_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='LifecycleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(max_length=120, unique=True)),
                ('application_type', models.CharField(max_length=32)),
                ('scheme_code', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(max_length=32)),
                ('eligibility_snapshot', models.JSONField(default=dict)),
                ('requested_credits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_status', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_applications', to='academic_lifecycle.studentprofile')),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='academic_lifecycle_lifecycleapplication_version_gte_1'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='academic_lifecycle_lifecycleapplication_effective_period_valid')],
            },
        ),
    ]
