"""Timeline_Engine service layer.

All Timeline_Engine business logic lives here (Requirement 18.4): template
instantiation, the task-status state machine, hard/soft dependency handling,
fixed/relative deadline resolution, non-destructive schedule history, and the
Home next-best-work grouping. Views and cross-module callers depend only on
these methods and the returned DTOs; they never touch the ORM directly.
"""

from __future__ import annotations

from datetime import date, timedelta

from django.db import transaction

from core.models import DemoUser

from . import validators
from .dtos import (
    CycleDTO,
    ExplanationDTO,
    HomeGroupsDTO,
    ScheduleChangeDTO,
    TaskDTO,
)
from .models import (
    ChecklistItem,
    DeadlineKind,
    DependencyKind,
    Milestone,
    OBECycle,
    Phase,
    ScheduleChange,
    Task,
    TaskDependency,
    TaskStatus,
    TimelineInstance,
    TimelineTemplate,
)

# Statuses that reflect explicit, in-progress user action. ``recompute_statuses``
# preserves these rather than overwriting them with derived readiness.
_ACTIVE_STATUSES = {
    TaskStatus.DIKERJAKAN,
    TaskStatus.DIAJUKAN,
    TaskStatus.PERLU_REVISI,
}


# ---------------------------------------------------------------------------
# Explanation helpers (guarantee the six-facet completeness of Property 13)
# ---------------------------------------------------------------------------

def _explanation_for(task: Task) -> ExplanationDTO:
    """Build a complete six-facet explanation, filling sensible defaults.

    Every facet is guaranteed non-empty so any task presented in Home or
    generated by the system satisfies explanation completeness (Property 13).
    """
    owner_name = task.owner.name if task.owner_id else "Belum ditetapkan"
    if task.resolved_deadline:
        when_default = f"Jatuh tempo pada {task.resolved_deadline:%d %b %Y}."
    else:
        when_default = "Jadwal belum ditetapkan."
    checklist = list(task.checklist_items.all())
    if checklist:
        how_default = "Selesaikan butir: " + ", ".join(c.text for c in checklist) + "."
    else:
        how_default = "Kerjakan tugas hingga tuntas lalu tandai selesai."

    return ExplanationDTO(
        what=(task.explanation_what or task.title).strip(),
        why=(task.explanation_why
             or "Tugas ini menjaga siklus OBE tetap berjalan sesuai rencana.").strip(),
        who=(task.explanation_who or owner_name).strip(),
        when=(task.explanation_when or when_default).strip(),
        how=(task.explanation_how or how_default).strip(),
        next=(task.explanation_next
              or "Setelah selesai, tugas berikutnya menjadi siap dikerjakan.").strip(),
    )


def _to_task_dto(task: Task, advisories: list[str] | None = None) -> TaskDTO:
    return TaskDTO(
        id=task.id,
        title=task.title,
        status=task.status,
        status_label=TaskStatus(task.status).label,
        owner_name=task.owner.name if task.owner_id else None,
        resolved_deadline=task.resolved_deadline,
        is_complete=task.is_complete,
        explanation=_explanation_for(task),
        advisories=list(advisories or []),
    )


class TimelineService:
    """Business logic for the Timeline_Engine."""

    # -- Instantiation (Requirements 1.1-1.5) ----------------------------

    @staticmethod
    @transaction.atomic
    def create_cycle_from_template(template_id, cycle_data, actor) -> CycleDTO:
        """Deep-copy a template into a new instance bound to a new cycle.

        Copies every phase, milestone, task, checklist item, and dependency
        edge, remapping dependency references to the newly created instance
        tasks (Requirements 1.1, 1.4), and binds the instance to exactly one
        cycle (Requirement 1.2). Rejects a template with no phase *before any
        write* (Requirement 1.5).
        """
        template = TimelineTemplate.objects.get(pk=template_id)

        template_phases = list(
            template.phases.all().prefetch_related("milestones__tasks__checklist_items")
        )
        if not template_phases:
            # Validate before any write (Requirement 1.5).
            raise validators.error_template_without_phase(template.name)

        actor_obj = _resolve_actor(actor)
        prodi = cycle_data.get("prodi") or (actor_obj.prodi if actor_obj else None)

        cycle = OBECycle.objects.create(
            name=cycle_data.get("name", template.name),
            academic_year=cycle_data.get("academic_year", ""),
            start_date=cycle_data.get("start_date"),
            prodi=prodi,
            owner=actor_obj,
            creator=actor_obj,
            status=cycle_data.get("status", "active"),
        )
        instance = TimelineInstance.objects.create(template=template, cycle=cycle)

        # Maps from template row -> newly created instance row, so dependency
        # edges and relative references can be remapped after the copy.
        task_map: dict[int, Task] = {}
        milestone_map: dict[int, Milestone] = {}
        # Tasks whose relative reference must be remapped after all tasks exist.
        relative_task_refs: list[tuple[Task, int]] = []

        for t_phase in template_phases:
            new_phase = Phase.objects.create(
                instance=instance, name=t_phase.name, order=t_phase.order
            )
            for t_ms in t_phase.milestones.all():
                new_ms = Milestone.objects.create(
                    phase=new_phase,
                    name=t_ms.name,
                    milestone_date=t_ms.milestone_date,
                    order=t_ms.order,
                )
                milestone_map[t_ms.id] = new_ms
                for t_task in t_ms.tasks.all():
                    new_task = Task.objects.create(
                        milestone=new_ms,
                        title=t_task.title,
                        owner=t_task.owner,
                        status=TaskStatus.BELUM_SIAP,
                        is_complete=False,
                        order=t_task.order,
                        deadline_kind=t_task.deadline_kind,
                        fixed_date=t_task.fixed_date,
                        relative_offset_days=t_task.relative_offset_days,
                        relative_reference_milestone=(
                            milestone_map.get(t_task.relative_reference_milestone_id)
                        ),
                        explanation_what=t_task.explanation_what,
                        explanation_why=t_task.explanation_why,
                        explanation_who=t_task.explanation_who,
                        explanation_when=t_task.explanation_when,
                        explanation_how=t_task.explanation_how,
                        explanation_next=t_task.explanation_next,
                    )
                    task_map[t_task.id] = new_task
                    if t_task.relative_reference_task_id:
                        relative_task_refs.append(
                            (new_task, t_task.relative_reference_task_id)
                        )

        # Remap relative task references now that every task exists.
        for new_task, old_ref_id in relative_task_refs:
            ref = task_map.get(old_ref_id)
            if ref is not None:
                new_task.relative_reference_task = ref
                new_task.save(update_fields=["relative_reference_task"])

        # Copy checklist items.
        for old_task_id, new_task in task_map.items():
            source_items = ChecklistItem.objects.filter(task_id=old_task_id)
            for item in source_items:
                ChecklistItem.objects.create(
                    task=new_task,
                    text=item.text,
                    is_complete=False,
                    order=item.order,
                )

        # Copy dependency edges, remapping predecessor/successor to new tasks.
        dep_count = 0
        edges = TaskDependency.objects.filter(predecessor_id__in=task_map.keys())
        for edge in edges:
            pred = task_map.get(edge.predecessor_id)
            succ = task_map.get(edge.successor_id)
            if pred is not None and succ is not None:
                TaskDependency.objects.create(
                    predecessor=pred, successor=succ, kind=edge.kind
                )
                dep_count += 1

        # Resolve deadlines and derive initial statuses for the fresh instance.
        TimelineService._resolve_all_deadlines(instance)
        TimelineService.recompute_statuses(instance.id)

        return CycleDTO(
            cycle_id=cycle.id,
            instance_id=instance.id,
            name=cycle.name,
            academic_year=cycle.academic_year,
            phase_count=instance.phases.count(),
            milestone_count=Milestone.objects.filter(phase__instance=instance).count(),
            task_count=Task.objects.filter(milestone__phase__instance=instance).count(),
            dependency_count=dep_count,
        )

    # -- Task status state machine (Requirements 2.2-2.7, 3.2) -----------

    @staticmethod
    @transaction.atomic
    def transition_to_dikerjakan(task_id, actor=None) -> TaskDTO:
        """Move a task to Dikerjakan; blocked by incomplete hard deps (Req 3.2).

        Incomplete *soft* dependencies never block; instead an advisory naming
        each incomplete predecessor is returned (Requirement 3.3).
        """
        task = Task.objects.get(pk=task_id)
        incomplete_hard = TimelineService._incomplete_hard_predecessors(task)
        if incomplete_hard:
            raise validators.error_hard_dependency_blocks(
                [t.title for t in incomplete_hard]
            )
        advisories = TimelineService._soft_dependency_advisories(task)
        task.status = TaskStatus.DIKERJAKAN
        task.save(update_fields=["status"])
        return _to_task_dto(task, advisories=advisories)

    @staticmethod
    @transaction.atomic
    def submit_task(task_id, actor=None) -> TaskDTO:
        """Submit a task for review -> Diajukan (Requirement 2.4)."""
        task = Task.objects.get(pk=task_id)
        task.status = TaskStatus.DIAJUKAN
        task.save(update_fields=["status"])
        return _to_task_dto(task)

    @staticmethod
    @transaction.atomic
    def return_task_for_revision(task_id, actor=None) -> TaskDTO:
        """Return a submitted task for changes -> Perlu Revisi (Requirement 2.5)."""
        task = Task.objects.get(pk=task_id)
        if task.status != TaskStatus.DIAJUKAN:
            raise validators.error_invalid_submit_state(
                TaskStatus(task.status).label
            )
        task.status = TaskStatus.PERLU_REVISI
        task.save(update_fields=["status"])
        return _to_task_dto(task)

    @staticmethod
    @transaction.atomic
    def complete_task(task_id, actor=None) -> TaskDTO:
        """Mark a task complete -> Selesai iff all checklist items complete.

        Selesai is reached if and only if the task is marked complete and every
        checklist item is complete (Requirement 2.7, Property 8).
        """
        task = Task.objects.get(pk=task_id)
        open_items = list(
            task.checklist_items.filter(is_complete=False).values_list("text", flat=True)
        )
        if open_items:
            raise validators.error_checklist_incomplete(open_items)
        task.is_complete = True
        task.status = TaskStatus.SELESAI
        task.save(update_fields=["is_complete", "status"])
        return _to_task_dto(task)

    @staticmethod
    @transaction.atomic
    def recompute_statuses(instance_id, today: date | None = None) -> None:
        """Recompute derived statuses across an instance.

        Derives Belum Siap / Siap Dikerjakan from hard-dependency completion
        (Requirements 2.2, 2.3) and Terlambat from overdue-and-not-Selesai
        (Requirement 2.6). Explicit action statuses (Dikerjakan, Diajukan,
        Perlu Revisi) and the terminal Selesai are preserved unless overdue.
        """
        today = today or date.today()
        tasks = list(
            Task.objects.filter(milestone__phase__instance_id=instance_id)
        )
        for task in tasks:
            new_status = TimelineService._derive_status(task, today)
            if new_status != task.status:
                task.status = new_status
                task.save(update_fields=["status"])

    @staticmethod
    def _derive_status(task: Task, today: date) -> str:
        """Compute the derived status for a single task."""
        if task.status == TaskStatus.SELESAI:
            return TaskStatus.SELESAI

        overdue = task.resolved_deadline is not None and task.resolved_deadline < today
        if overdue:
            # Overdue and not Selesai -> Terlambat (Requirement 2.6, Property 7).
            return TaskStatus.TERLAMBAT

        if TimelineService._incomplete_hard_predecessors(task):
            # A hard dependency is not yet Selesai (Requirement 2.2, Property 5).
            return TaskStatus.BELUM_SIAP

        # All hard dependencies complete. Preserve in-progress action states;
        # otherwise the task is ready (Requirement 2.3, Property 6).
        if task.status in _ACTIVE_STATUSES:
            return task.status
        return TaskStatus.SIAP_DIKERJAKAN

    # -- Dependency helpers (Requirements 3.1-3.3) -----------------------

    @staticmethod
    def _incomplete_hard_predecessors(task: Task) -> list[Task]:
        """Predecessors of ``task`` on hard edges that are not yet Selesai."""
        deps = TaskDependency.objects.filter(
            successor=task, kind=DependencyKind.HARD
        ).select_related("predecessor")
        return [
            dep.predecessor
            for dep in deps
            if dep.predecessor.status != TaskStatus.SELESAI
        ]

    @staticmethod
    def _incomplete_soft_predecessors(task: Task) -> list[Task]:
        """Predecessors of ``task`` on soft edges that are not yet Selesai."""
        deps = TaskDependency.objects.filter(
            successor=task, kind=DependencyKind.SOFT
        ).select_related("predecessor")
        return [
            dep.predecessor
            for dep in deps
            if dep.predecessor.status != TaskStatus.SELESAI
        ]

    @staticmethod
    def _soft_dependency_advisories(task: Task) -> list[str]:
        """Advisories naming each incomplete soft predecessor (Requirement 3.3)."""
        return [
            (
                f"Disarankan menyelesaikan \u201c{pred.title}\u201d terlebih dahulu, "
                "namun tugas ini tetap dapat dikerjakan."
            )
            for pred in TimelineService._incomplete_soft_predecessors(task)
        ]

    @staticmethod
    def work_advisories(task_id) -> list[str]:
        """Public accessor for the soft-dependency advisories of a task."""
        task = Task.objects.get(pk=task_id)
        return TimelineService._soft_dependency_advisories(task)

    # -- Deadlines: fixed vs relative (Requirements 3.4, 3.5) ------------

    @staticmethod
    def _reference_date_for(task: Task) -> date | None:
        """The reference date a relative deadline is measured from."""
        if task.relative_reference_milestone_id:
            return task.relative_reference_milestone.milestone_date
        if task.relative_reference_task_id:
            ref = task.relative_reference_task
            return ref.resolved_deadline or TimelineService._compute_resolved(ref)
        return None

    @staticmethod
    def _compute_resolved(task: Task) -> date | None:
        """Compute a task's resolved deadline from its fixed/relative config."""
        if task.deadline_kind == DeadlineKind.FIXED:
            return task.fixed_date
        reference = TimelineService._reference_date_for(task)
        if reference is None or task.relative_offset_days is None:
            return None
        return reference + timedelta(days=task.relative_offset_days)

    @staticmethod
    def _resolve_all_deadlines(instance: TimelineInstance) -> None:
        """Resolve every task deadline in an instance (handles simple chains)."""
        tasks = list(Task.objects.filter(milestone__phase__instance=instance))
        # A few passes resolves relative-to-relative reference chains.
        for _ in range(len(tasks) + 1):
            changed = False
            for task in tasks:
                resolved = TimelineService._compute_resolved(task)
                if resolved != task.resolved_deadline:
                    task.resolved_deadline = resolved
                    task.save(update_fields=["resolved_deadline"])
                    changed = True
            if not changed:
                break

    @staticmethod
    @transaction.atomic
    def recompute_relative_deadlines(instance_id) -> None:
        """Recompute resolved deadlines for every task in an instance (Req 3.5)."""
        instance = TimelineInstance.objects.get(pk=instance_id)
        TimelineService._resolve_all_deadlines(instance)

    # -- Non-destructive schedule history (Requirements 5.1-5.4) ---------

    @staticmethod
    @transaction.atomic
    def change_schedule(
        target_kind: str, target_id, new_deadline: date | None, reason: str, actor=None
    ) -> ScheduleChangeDTO:
        """Record a non-destructive schedule change and recompute dependents.

        Retains the previous value, requires and stores a reason, and records
        the actor, timestamp, previous value, and new value (Requirements
        5.1-5.3). Recomputes dependent relative deadlines afterwards (Req 3.5).
        """
        if not (reason or "").strip():
            raise validators.error_reason_required()

        actor_obj = _resolve_actor(actor)

        if target_kind == "milestone":
            milestone = Milestone.objects.get(pk=target_id)
            previous = milestone.milestone_date
            change = ScheduleChange.objects.create(
                milestone=milestone,
                actor=actor_obj,
                previous_value=previous,
                new_value=new_deadline,
                reason=reason.strip(),
            )
            milestone.milestone_date = new_deadline
            milestone.save(update_fields=["milestone_date"])
            instance = milestone.phase.instance
            target_name = milestone.name
        else:
            task = Task.objects.get(pk=target_id)
            previous = task.resolved_deadline
            change = ScheduleChange.objects.create(
                task=task,
                actor=actor_obj,
                previous_value=previous,
                new_value=new_deadline,
                reason=reason.strip(),
            )
            # A direct schedule change pins the task to a fixed date.
            task.deadline_kind = DeadlineKind.FIXED
            task.fixed_date = new_deadline
            task.resolved_deadline = new_deadline
            task.save(
                update_fields=["deadline_kind", "fixed_date", "resolved_deadline"]
            )
            instance = task.milestone.phase.instance
            target_name = task.title

        if instance is not None:
            TimelineService._resolve_all_deadlines(instance)

        return ScheduleChangeDTO(
            id=change.id,
            target_kind=target_kind,
            target_id=target_id,
            target_name=target_name,
            actor_name=actor_obj.name if actor_obj else None,
            timestamp=change.timestamp,
            previous_value=change.previous_value,
            new_value=change.new_value,
            reason=change.reason,
        )

    @staticmethod
    def get_history(instance_id) -> list[ScheduleChangeDTO]:
        """Return the instance's schedule changes newest-first (Requirement 5.4)."""
        changes = ScheduleChange.objects.filter(
            models_q_instance(instance_id)
        ).select_related("actor", "task", "milestone").order_by("-timestamp", "-id")

        result: list[ScheduleChangeDTO] = []
        for change in changes:
            if change.task_id:
                target_kind = "task"
                target_id = change.task_id
                target_name = change.task.title
            else:
                target_kind = "milestone"
                target_id = change.milestone_id
                target_name = change.milestone.name
            result.append(
                ScheduleChangeDTO(
                    id=change.id,
                    target_kind=target_kind,
                    target_id=target_id,
                    target_name=target_name,
                    actor_name=change.actor.name if change.actor_id else None,
                    timestamp=change.timestamp,
                    previous_value=change.previous_value,
                    new_value=change.new_value,
                    reason=change.reason,
                )
            )
        return result


class HomeService:
    """Next-best-work grouping for the Home workspace (Requirements 4.1-4.5)."""

    # Status -> Home bucket mapping (Property 12).
    _DO_NOW = {TaskStatus.SIAP_DIKERJAKAN, TaskStatus.DIKERJAKAN}
    _NEXT = {TaskStatus.BELUM_SIAP}
    _WAITING = {TaskStatus.DIAJUKAN}

    @classmethod
    def next_best_work(cls, demo_user_id) -> HomeGroupsDTO:
        """Partition the user's tasks into Do Now / Next / Waiting on Others.

        Each task carries a complete six-facet explanation (Requirement 4.5).
        """
        if not demo_user_id:
            return HomeGroupsDTO()

        tasks = list(
            Task.objects.filter(owner_id=demo_user_id)
            .select_related("owner")
            .prefetch_related("checklist_items")
            .order_by("resolved_deadline", "id")
        )

        do_now: list[TaskDTO] = []
        nxt: list[TaskDTO] = []
        waiting: list[TaskDTO] = []
        for task in tasks:
            if task.status in cls._DO_NOW:
                do_now.append(_to_task_dto(task))
            elif task.status in cls._NEXT:
                nxt.append(_to_task_dto(task))
            elif task.status in cls._WAITING:
                waiting.append(_to_task_dto(task))
        return HomeGroupsDTO(do_now=do_now, next=nxt, waiting_on_others=waiting)


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def _resolve_actor(actor) -> DemoUser | None:
    """Accept a DemoUser instance or an id and return the DemoUser (or None)."""
    if actor is None:
        return None
    if isinstance(actor, DemoUser):
        return actor
    return DemoUser.objects.filter(pk=actor).first()


def models_q_instance(instance_id):
    """Q object selecting schedule changes belonging to an instance."""
    from django.db.models import Q

    return Q(task__milestone__phase__instance_id=instance_id) | Q(
        milestone__phase__instance_id=instance_id
    )
