# Generated by Django 5.1.15 on 2026-07-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInjectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('load', 'Load'), ('reset', 'Reset')], default='load', max_length=16)),
                ('command', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Injection Log',
                'verbose_name_plural': 'Data Injection Logs',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Program of Study',
                'verbose_name_plural': 'Programs of Study',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConfigRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('rule', 'Validation Rule'), ('standard', 'Standard'), ('formula', 'Calculation Formula')], default='rule', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuration Record',
                'verbose_name_plural': 'Configuration Records',
                'ordering': ['key', '-version'],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='uniq_configrecord_key_version')],
            },
        ),
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('kaprodi', 'Kaprodi'), ('lecturer', 'Dosen Pengampu'), ('dev_admin', 'Dev Administrator')], max_length=32)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demo_users', to='core.programofstudy')),
            ],
            options={
                'verbose_name': 'Demo User',
                'verbose_name_plural': 'Demo Users',
                'ordering': ['role', 'name'],
            },
        ),
    ]
