# Generated by Django 5.1.15 on 2026-07-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Template',
                'verbose_name_plural': 'Timeline Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OBECycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
            ],
            options={
                'verbose_name': 'OBE Cycle',
                'verbose_name_plural': 'OBE Cycles',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('milestone_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='timeline.phase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('belum_siap', 'Belum Siap'), ('siap_dikerjakan', 'Siap Dikerjakan'), ('dikerjakan', 'Dikerjakan'), ('diajukan', 'Diajukan'), ('perlu_revisi', 'Perlu Revisi'), ('selesai', 'Selesai'), ('terhambat', 'Terhambat'), ('terlambat', 'Terlambat')], default='belum_siap', max_length=32)),
                ('is_complete', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('deadline_kind', models.CharField(choices=[('fixed', 'Tanggal Tetap'), ('relative', 'Tanggal Relatif')], default='fixed', max_length=16)),
                ('fixed_date', models.DateField(blank=True, null=True)),
                ('relative_offset_days', models.IntegerField(blank=True, null=True)),
                ('resolved_deadline', models.DateField(blank=True, null=True)),
                ('explanation_what', models.TextField(blank=True)),
                ('explanation_why', models.TextField(blank=True)),
                ('explanation_who', models.TextField(blank=True)),
                ('explanation_when', models.TextField(blank=True)),
                ('explanation_how', models.TextField(blank=True)),
                ('explanation_next', models.TextField(blank=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timeline.milestone')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('relative_reference_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.milestone')),
                ('relative_reference_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timeline.task')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.DateField(blank=True, null=True)),
                ('new_value', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_changes', to='timeline.milestone')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_changes', to='timeline.task')),
            ],
            options={
                'verbose_name': 'Schedule Change',
                'verbose_name_plural': 'Schedule Changes',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='timeline.task')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_instance', to='timeline.obecycle')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='timeline.timelinetemplate')),
            ],
            options={
                'verbose_name': 'Timeline Instance',
                'verbose_name_plural': 'Timeline Instances',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='timeline.timelineinstance'),
        ),
        migrations.AddField(
            model_name='phase',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='timeline.timelinetemplate'),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=8)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='timeline.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='timeline.task')),
            ],
            options={
                'verbose_name': 'Task Dependency',
                'verbose_name_plural': 'Task Dependencies',
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor', 'kind'), name='uniq_taskdependency_edge')],
            },
        ),
    ]
