# Generated by Django 6.0.7 on 2026-07-19 04:47

from django.db import migrations, models


def assert_manifest_versions_unique(apps, schema_editor):
    FileManifest = apps.get_model("shared", "FileManifest")
    duplicate = (
        FileManifest.objects.values("academic_object", "version")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .order_by("academic_object", "version")
        .first()
    )
    if duplicate:
        raise RuntimeError(
            "Duplikat academic_object/version harus direkonsiliasi sebelum migration: "
            f"{duplicate['academic_object']} v{duplicate['version']}"
        )


def reverse_assert_manifest_versions_unique(apps, schema_editor):
    assert_manifest_versions_unique(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filemanifest',
            name='manifest_object_version_unique',
        ),
        migrations.AddField(
            model_name='academicrule',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='academicrule',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='filemanifest',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filemanifest',
            name='scan_status',
            field=models.CharField(choices=[('skipped', 'Skipped'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='skipped', max_length=16),
        ),
        migrations.AddField(
            model_name='filemanifest',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filemanifest',
            name='scanner_signature',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='filemanifest',
            name='classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted-exam', 'Restricted Exam')], default='internal', max_length=32),
        ),
        migrations.AlterField(
            model_name='filemanifest',
            name='content_path',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(
            assert_manifest_versions_unique,
            reverse_code=reverse_assert_manifest_versions_unique,
        ),
        migrations.AddIndex(
            model_name='filemanifest',
            index=models.Index(fields=['owner_id', 'created_at'], name='shared_file_owner_i_c9dacb_idx'),
        ),
        migrations.AddConstraint(
            model_name='filemanifest',
            constraint=models.UniqueConstraint(fields=('academic_object', 'version'), name='manifest_object_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='filemanifest',
            constraint=models.CheckConstraint(condition=models.Q(('size__gt', 0)), name='manifest_size_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='filemanifest',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='manifest_version_gte_1'),
        ),
    ]
