# Generated by Django 6.0.7 on 2026-07-19 05:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_remove_filemanifest_manifest_object_version_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=80)),
                ('event_type', models.CharField(max_length=160)),
                ('aggregate_id', models.CharField(max_length=80)),
                ('last_version', models.PositiveIntegerField(default=0)),
                ('last_event_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('consumer', models.CharField(max_length=80)),
                ('event_type', models.CharField(max_length=160)),
                ('aggregate_id', models.CharField(max_length=80)),
                ('aggregate_version', models.PositiveIntegerField()),
                ('payload_schema', models.CharField(max_length=40)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('failed', 'Failed')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=160)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(db_index=True, max_length=180)),
                ('queue', models.CharField(db_index=True, max_length=40)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='consumers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='last_error',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='next_attempt_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('published', 'Published'), ('dead', 'Dead')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='sensitivity',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='internal', max_length=32),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'next_attempt_at', 'occurred_at'], name='shared_outb_status_82db4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('aggregate_version__gte', 1)), name='outbox_aggregate_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', 100)), name='outbox_attempts_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='consumercursor',
            constraint=models.UniqueConstraint(fields=('consumer', 'event_type', 'aggregate_id'), name='consumer_cursor_unique'),
        ),
        migrations.AddIndex(
            model_name='inboxevent',
            index=models.Index(fields=['consumer', 'event_type', 'aggregate_id'], name='shared_inbo_consume_095eb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboxevent',
            constraint=models.UniqueConstraint(fields=('consumer', 'event_id'), name='inbox_consumer_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='inboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('aggregate_version__gte', 1)), name='inbox_aggregate_version_gte_1'),
        ),
        migrations.AddIndex(
            model_name='jobexecution',
            index=models.Index(fields=['status', 'lease_expires_at'], name='shared_jobe_status_07e1d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobexecution',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='job_progress_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='jobexecution',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='job_generation_gte_1'),
        ),
    ]
