# Generated by Django 6.0.7 on 2026-07-19 06:35

import django.db.models.deletion
import django.utils.timezone
import hashlib
import json
from django.db import migrations, models


def install_append_only_guard(apps, schema_editor):
    AuditEvent = apps.get_model("shared", "AuditEvent")
    previous_hash = "0" * 64
    for event in AuditEvent.objects.order_by("occurred_at", "id").iterator():
        event.previous_hash = previous_hash
        payload = {
            "id": str(event.id),
            "actor_id": event.actor_id,
            "actor_label": event.actor_label,
            "actor_scope": event.actor_scope,
            "actor_role": event.actor_role,
            "assignment_reference": event.assignment_reference,
            "action": event.action,
            "object_type": event.object_type,
            "object_id": event.object_id,
            "summary": event.summary,
            "before": event.before,
            "after": event.after,
            "reason": event.reason,
            "correlation_id": str(event.correlation_id),
            "ip_address": str(event.ip_address or ""),
            "user_agent": event.user_agent,
            "outcome": event.outcome,
            "occurred_at": event.occurred_at.isoformat(),
            "retention_until": str(event.retention_until or ""),
            "previous_hash": previous_hash,
        }
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
        event.integrity_hash = hashlib.sha256(canonical.encode()).hexdigest()
        AuditEvent.objects.filter(pk=event.pk).update(
            previous_hash=event.previous_hash,
            integrity_hash=event.integrity_hash,
        )
        previous_hash = event.integrity_hash

    table = schema_editor.quote_name(AuditEvent._meta.db_table)
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(
            f"CREATE TRIGGER shared_audit_no_update BEFORE UPDATE ON {table} "
            "BEGIN SELECT RAISE(ABORT, 'audit append-only'); END"
        )
    elif schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE FUNCTION shared_reject_audit_mutation() RETURNS trigger AS $$ "
            "BEGIN RAISE EXCEPTION 'audit append-only'; END; $$ LANGUAGE plpgsql"
        )
        schema_editor.execute(
            f"CREATE TRIGGER shared_audit_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION shared_reject_audit_mutation()"
        )


def uninstall_append_only_guard(apps, schema_editor):
    AuditEvent = apps.get_model("shared", "AuditEvent")
    table = schema_editor.quote_name(AuditEvent._meta.db_table)
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS shared_audit_no_update")
    elif schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS shared_audit_append_only ON {table}")
        schema_editor.execute("DROP FUNCTION IF EXISTS shared_reject_audit_mutation()")


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_consumercursor_inboxevent_jobexecution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="occurred_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_role',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='assignment_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='retention_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='kill_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='target_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='authorization_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='feature_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AuditSensitivePayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('classification', models.CharField(default='confidential', max_length=32)),
                ('retention_until', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_payload', to='shared.auditevent')),
            ],
        ),
        migrations.CreateModel(
            name='AuditReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='shared.auditevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'audit'), name='audit_reference_unique')],
            },
        ),
        migrations.RunPython(install_append_only_guard, uninstall_append_only_guard),
    ]
