# Generated by Django 6.0.7 on 2026-07-19 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_auditevent_actor_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrule',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicrule',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicrule',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcademicDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.CharField(db_index=True, max_length=80)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('indeterminate', 'Indeterminate')], max_length=20)),
                ('reason_code', models.CharField(db_index=True, max_length=100)),
                ('evidence_rows', models.JSONField(default=list)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('calculation_trace', models.JSONField(default=list)),
                ('source_versions', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField()),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('decision_hash', models.CharField(max_length=64, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='shared.academicrule')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAppeal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('information-needed', 'Information needed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('closed', 'Closed')], default='submitted', max_length=24)),
                ('statement', models.TextField()),
                ('evidence_documents', models.JSONField(default=list)),
                ('information_request', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals_submitted', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='shared.academicdecision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CohortRulePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('cohort_from', models.PositiveSmallIntegerField()),
                ('cohort_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_scheme', models.JSONField(default=list)),
                ('minimum_passing_grade', models.CharField(default='C', max_length=4)),
                ('minimum_thesis_grade', models.CharField(default='B', max_length=4)),
                ('irs_policy', models.JSONField(blank=True, default=dict)),
                ('progress_milestones', models.JSONField(blank=True, default=list)),
                ('graduation_policy', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_packages_activated', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_packages_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='academicdecision',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='shared.cohortrulepackage'),
        ),
        migrations.CreateModel(
            name='DecisionOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='submitted', max_length=20)),
                ('reason_code', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('evidence_documents', models.JSONField(default=list)),
                ('impact', models.TextField()),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides_checked', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='shared.academicdecision')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='cohortrulepackage',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='rule_package_version_unique'),
        ),
        migrations.AddIndex(
            model_name='academicdecision',
            index=models.Index(fields=['object_type', 'object_id', 'created_at'], name='shared_acad_object__b5e6a8_idx'),
        ),
    ]
