# Generated by Django 5.2.16 on 2026-07-19 21:53

from django.db import migrations, models


def install_append_only_guard(apps, schema_editor):
    """Restore the database guard after SQLite rebuilds the audit table."""
    AuditEvent = apps.get_model("shared", "AuditEvent")
    table = schema_editor.quote_name(AuditEvent._meta.db_table)
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS shared_audit_no_update")
        schema_editor.execute(
            f"CREATE TRIGGER shared_audit_no_update BEFORE UPDATE ON {table} "
            "BEGIN SELECT RAISE(ABORT, 'audit append-only'); END"
        )
    elif schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS shared_audit_append_only ON {table}"
        )
        schema_editor.execute(
            "CREATE OR REPLACE FUNCTION shared_reject_audit_mutation() "
            "RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'audit append-only'; "
            "END; $$ LANGUAGE plpgsql"
        )
        schema_editor.execute(
            f"CREATE TRIGGER shared_audit_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION shared_reject_audit_mutation()"
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_academicrule_activated_at_academicrule_review_note_and_more'),
    ]

    operations = [
        # The reverse hook runs after reverse AddField operations rebuild the
        # SQLite table, so the PR-13 append-only invariant also survives a
        # deterministic backward migration.
        migrations.RunPython(noop, install_append_only_guard),
        migrations.AddField(
            model_name='auditevent',
            name='source_event_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='source_previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='decisionoverride',
            name='source_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='source_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='filemanifest',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filemanifest',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(install_append_only_guard, noop),
    ]
