# Generated by Django 6.0.7 on 2026-07-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
