# Generated by Django 5.2.16 on 2026-07-19 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_courseoffering_created_by_actor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='curriculum_version_public_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='approved_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='content_checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='returned_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='reviewed_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='assignment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='execution_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='rescheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_plans_rescheduled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='rescheduled_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('bloom_level', models.CharField(max_length=32)),
                ('target', models.DecimalField(decimal_places=2, default=75, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('program_cpmk_ids', models.JSONField(default=list)),
                ('cpl_ids', models.JSONField(default=list)),
                ('status', models.CharField(default='active', max_length=20)),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_outcomes', to='learning.rpsversion')),
            ],
        ),
        migrations.CreateModel(
            name='RPSFieldComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=160)),
                ('comment', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rps_comments_resolved', to=settings.AUTH_USER_MODEL)),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_comments', to='learning.rpsversion')),
            ],
        ),
        migrations.CreateModel(
            name='SubOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('bloom_level', models.CharField(max_length=32)),
                ('target', models.DecimalField(decimal_places=2, default=75, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=20)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_outcomes', to='learning.courseoutcome')),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_outcomes', to='learning.rpsversion')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('measurement', models.CharField(default='normalized-score-0-100', max_length=80)),
                ('target', models.DecimalField(decimal_places=2, default=75, max_digits=6)),
                ('observable', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=20)),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='learning.rpsversion')),
                ('sub_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='learning.suboutcome')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseoutcome',
            constraint=models.UniqueConstraint(fields=('rps', 'code'), name='rps_course_outcome_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='suboutcome',
            constraint=models.UniqueConstraint(fields=('rps', 'code'), name='rps_sub_outcome_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='performanceindicator',
            constraint=models.UniqueConstraint(fields=('rps', 'code'), name='rps_indicator_code_unique'),
        ),
    ]
