# Generated by Django 5.2.16 on 2026-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_courseoffering_curriculum_version_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='calendar_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='delivery_mode',
            field=models.CharField(choices=[('regular', 'Regular'), ('short', 'Short semester')], default='regular', max_length=16),
        ),
    ]
