# Generated by Django 5.2.16 on 2026-07-19 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_courseoffering_calendar_configuration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source_version',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rpsversion',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ExamEligibilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('reason_code', models.CharField(max_length=80)),
                ('reason', models.TextField()),
                ('evidence_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_overrides_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferingRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('student_id', models.CharField(max_length=64)),
                ('enrollment_plan_public_id', models.UUIDField(blank=True, null=True)),
                ('irs_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('missing', 'Missing'), ('rejected', 'Rejected')], default='missing', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=16)),
                ('source_version', models.JSONField(blank=True, default=dict)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_entries', to='learning.courseoffering')),
            ],
        ),
        migrations.CreateModel(
            name='ExamEligibilitySnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eligible', models.BooleanField()),
                ('attendance_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('attended', models.PositiveIntegerField()),
                ('denominator', models.PositiveIntegerField()),
                ('counted_activity_ids', models.JSONField(default=list)),
                ('reason_codes', models.JSONField(default=list)),
                ('rule_code', models.CharField(default='ATTENDANCE-UAS-75', max_length=80)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('source_versions', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_snapshots', to='learning.exameligibilityoverride')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_snapshots', to='learning.offeringroster')),
            ],
        ),
        migrations.AddField(
            model_name='exameligibilityoverride',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_overrides', to='learning.offeringroster'),
        ),
        migrations.AddConstraint(
            model_name='offeringroster',
            constraint=models.UniqueConstraint(fields=('offering', 'student_id', 'version'), name='offering_roster_student_version_unique'),
        ),
        migrations.AddIndex(
            model_name='exameligibilitysnapshot',
            index=models.Index(fields=['roster', 'created_at'], name='learning_ex_roster__47a64d_idx'),
        ),
        migrations.AddConstraint(
            model_name='exameligibilityoverride',
            constraint=models.UniqueConstraint(fields=('roster', 'reason_code', 'version'), name='exam_override_roster_reason_version_unique'),
        ),
    ]
