# Generated by Django 6.0.7 on 2026-07-19 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentinstrument',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='score',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='score',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='created_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='assessment_score_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='assessment_score_effective_period_valid'),
        ),
    ]
