# Generated by Django 5.2.16 on 2026-07-19 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentinstrument_created_by_actor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentinstrument',
            name='blueprint',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='evidence_class',
            field=models.CharField(default='assessment', max_length=32),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='first_score_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='mode',
            field=models.CharField(default='onsite', max_length=24),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='participant_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='rps_public_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='rubric_public_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='blind_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='score',
            name='moderation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='moderation_state',
            field=models.CharField(default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='score',
            name='reconciliation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='score',
            name='second_assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scores_second_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('analytic', 'Analytic'), ('holistic', 'Holistic'), ('checklist', 'Checklist'), ('numeric', 'Numeric'), ('pass_fail', 'Pass/Fail')], max_length=20)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='rubric_code_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('indicator_codes', models.JSONField(default=list)),
                ('sub_outcome_codes', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria', to='assessment.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weighted_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('feedback', models.TextField(blank=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterion_scores', to='assessment.score')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterion_scores', to='assessment.rubriccriterion')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('prompt', models.TextField()),
                ('item_type', models.CharField(max_length=24)),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difficulty', models.CharField(blank=True, max_length=16)),
                ('indicator_codes', models.JSONField(default=list)),
                ('sub_outcome_codes', models.JSONField(default=list)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assessment.assessmentinstrument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instrument', 'code'), name='instrument_item_code_unique')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=24)),
                ('descriptor', models.TextField()),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=7)),
                ('maximum', models.DecimalField(decimal_places=2, max_digits=7)),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='assessment.rubric')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rubric', 'code'), name='rubric_level_code_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'code'), name='rubric_criterion_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(fields=('score', 'criterion'), name='score_criterion_unique'),
        ),
    ]
