# Generated by Django 5.2.16 on 2026-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessmentinstrument_blueprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentinstrument',
            name='rubric',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
