# Generated by Django 5.2.16 on 2026-07-19 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessmentinstrument_rubric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentinstrument',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='score',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='calculation_trace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='score',
            name='competency_category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='score',
            name='rule_package',
            field=models.CharField(default='CURRENT-AABBC', max_length=32),
        ),
        migrations.AddField(
            model_name='score',
            name='rule_package_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='score',
            name='source_version',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions_reopened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_version',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='score',
            name='state',
            field=models.CharField(choices=[('graded', 'Graded'), ('absent', 'Absent'), ('exempt', 'Exempt'), ('not_graded', 'Not graded'), ('invalid', 'Invalid'), ('regraded', 'Regraded')], default='graded', max_length=20),
        ),
        migrations.CreateModel(
            name='CompetencyScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=40)),
                ('bands', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='competency_scale_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='ParallelExamPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('program_code', models.CharField(max_length=32)),
                ('strict_same_question', models.BooleanField(default=False)),
                ('disparity_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parallel_exam_policies_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parallel_exam_policies_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('parallel_group', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=40)),
                ('blueprint_checksum', models.CharField(max_length=64)),
                ('question_checksum', models.CharField(max_length=64)),
                ('coverage', models.JSONField(default=dict)),
                ('difficulty', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('gpm_review', 'GPM review'), ('approved', 'Approved'), ('released', 'Released')], default='draft', max_length=20)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_sets_authored', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_sets', to='assessment.assessmentinstrument')),
            ],
        ),
        migrations.CreateModel(
            name='ExamEquivalenceReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parallel_group', models.CharField(max_length=80)),
                ('exam_code', models.CharField(max_length=24)),
                ('equivalent', models.BooleanField(default=False)),
                ('equivalence_report', models.JSONField(default=dict)),
                ('difference_reason', models.TextField(blank=True)),
                ('result_analysis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('gpm_reviewed', 'GPM reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_equivalence_approved', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_equivalence_reviewed', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equivalence_reviews', to='assessment.parallelexampolicy')),
                ('question_sets', models.ManyToManyField(related_name='equivalence_reviews', to='assessment.questionsetversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_raw_score', models.DecimalField(decimal_places=3, max_digits=9)),
                ('proposed_max_score', models.DecimalField(decimal_places=3, max_digits=9)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('decision_reason', models.TextField(blank=True)),
                ('recalculation', models.JSONField(blank=True, default=dict)),
                ('notification_key', models.CharField(max_length=160, unique=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_revisions_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_revisions_requested', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_requests', to='assessment.score')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=40)),
                ('member_ids', models.JSONField(default=list)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_groups', to='assessment.assessmentinstrument')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assessment.submissiongroup'),
        ),
        migrations.AddConstraint(
            model_name='parallelexampolicy',
            constraint=models.UniqueConstraint(fields=('program_code', 'version'), name='parallel_exam_policy_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionsetversion',
            constraint=models.UniqueConstraint(fields=('instrument', 'code', 'version'), name='question_set_instrument_code_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='submissiongroup',
            constraint=models.UniqueConstraint(fields=('instrument', 'code', 'version'), name='submission_group_instrument_code_version_unique'),
        ),
    ]
