# Generated by Django 5.2.16 on 2026-07-20 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assessmentinstrument_deadline_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='contribution_summary',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='difference',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainment_snapshots_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='missing_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='previous_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recalculations', to='assessment.attainmentsnapshot'),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='recalculation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='snapshot_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('blocked', 'Blocked'), ('superseded', 'Superseded')], default='valid', max_length=16),
        ),
        migrations.CreateModel(
            name='AttainmentContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=120)),
                ('score_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('normalized', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weighted_value', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('path', models.JSONField(default=dict)),
                ('evidence_status', models.CharField(blank=True, max_length=32)),
                ('score_status', models.CharField(blank=True, max_length=32)),
                ('source_versions', models.JSONField(default=dict)),
                ('blocking_reasons', models.JSONField(default=list)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='assessment.attainmentsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='AttainmentFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=80)),
                ('scope_type', models.CharField(max_length=30)),
                ('distribution', models.JSONField(default=list)),
                ('target', models.DecimalField(decimal_places=2, default=75, max_digits=6)),
                ('source_versions', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainment_formulas_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attainment_formulas_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attainment_formulas_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attainmentsnapshot',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='assessment.attainmentformula'),
        ),
        migrations.AddConstraint(
            model_name='attainmentsnapshot',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'outcome_code', 'snapshot_version'), name='attainment_scope_outcome_snapshot_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='attainmentcontribution',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_id'), name='attainment_contribution_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='attainmentformula',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='attainment_formula_code_version_unique'),
        ),
    ]
