# Generated by Django 6.0.7 on 2026-07-19 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_improvementaction_created_by_actor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrityissue',
            name='fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='integrityissue',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integrityissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrityissue',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='integrityissue',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='integrityissue',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrityissue',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrity_issues_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integrityissue',
            name='severity',
            field=models.CharField(choices=[('blocking', 'Blocking error'), ('warning', 'Review warning'), ('information', 'Information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='integrityissue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('accepted-risk', 'Accepted risk'), ('reopened', 'Reopened'), ('verified', 'Verified')], default='open', max_length=24),
        ),
        migrations.CreateModel(
            name='IntegrityValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=160)),
                ('source_checksum', models.CharField(db_index=True, max_length=64)),
                ('validator_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='running', max_length=16)),
                ('statistics', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_checksum', 'validator_version'), name='integrity_run_checksum_version_unique')],
            },
        ),
    ]
