# Generated by Django 5.2.16 on 2026-07-19 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_integrityissue_fingerprint_integrityissue_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrityissue',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=80)),
                ('metric', models.CharField(max_length=80)),
                ('target', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='quality_standard_code_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='QualityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=160, unique=True)),
                ('scope', models.JSONField(default=dict)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gap', models.DecimalField(decimal_places=2, max_digits=8)),
                ('classification', models.CharField(max_length=40)),
                ('denominator', models.PositiveIntegerField(default=0)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='quality.qualitystandard')),
            ],
        ),
    ]
