# Generated by Django 5.2.16 on 2026-07-20 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_integrityissue_source_id_qualitystandard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementaction',
            name='accepted_risk_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='improvementaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='improvement_actions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='improvementaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvementaction',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvementaction',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='improvementaction',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='quality.qualityfinding'),
        ),
        migrations.AddField(
            model_name='improvementaction',
            name='reopened_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityfinding',
            name='confidence',
            field=models.CharField(default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='qualityfinding',
            name='coverage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='qualityfinding',
            name='reason_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='qualityfinding',
            name='status',
            field=models.CharField(default='open', max_length=24),
        ),
        migrations.AlterField(
            model_name='improvementaction',
            name='approval',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='improvementaction',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='quality.integrityissue'),
        ),
        migrations.AlterField(
            model_name='improvementaction',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='improvementaction',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('ineffective', 'Ineffective'), ('effective', 'Effective'), ('accepted-risk', 'Accepted risk'), ('reopened', 'Reopened')], default='planned', max_length=24),
        ),
        migrations.CreateModel(
            name='AcademicFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('reporter_fingerprint', models.CharField(blank=True, max_length=64)),
                ('anonymous', models.BooleanField(default=False)),
                ('retaliation_risk', models.BooleanField(default=False)),
                ('confidentiality', models.CharField(default='internal', max_length=24)),
                ('period', models.CharField(max_length=40)),
                ('course_offering_id', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('impact', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('clarification', 'Clarification'), ('action-planned', 'Action planned'), ('actioned', 'Actioned'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='new', max_length=24)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('linked_objects', models.JSONField(blank=True, default=list)),
                ('decision_reason', models.TextField(blank=True)),
                ('closure_evidence', models.JSONField(blank=True, default=list)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_feedback_submitted', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_feedback_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='quality_academicfeedback_version_gte_1'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='quality_academicfeedback_effective_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('portfolio_type', models.CharField(choices=[('student', 'Student'), ('course', 'Course'), ('program', 'Program')], max_length=16)),
                ('scope_id', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('gpm-review', 'GPM review'), ('returned', 'Returned for revision'), ('approved', 'Approved'), ('published', 'Published'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('sections', models.JSONField(default=dict)),
                ('source_versions', models.JSONField(blank=True, default=dict)),
                ('evidence_manifest_ids', models.JSONField(blank=True, default=list)),
                ('incomplete_sections', models.JSONField(blank=True, default=list)),
                ('package_checksum', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approval_history', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios_approved', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolios_generated', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='quality.portfoliosnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portfolio_type', 'scope_id', 'period', 'version'), name='portfolio_scope_period_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('period', models.CharField(max_length=40)),
                ('scope_type', models.CharField(max_length=40)),
                ('scope_id', models.CharField(max_length=80)),
                ('evaluation_type', models.CharField(default='formative', max_length=16)),
                ('sections', models.JSONField(default=dict)),
                ('source_versions', models.JSONField(blank=True, default=dict)),
                ('missing_sections', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('gpm-reviewed', 'GPM reviewed'), ('prodi-approved', 'Prodi approved'), ('tpmf-reviewed', 'TPMF reviewed'), ('published', 'Published'), ('correction', 'Correction')], default='draft', max_length=24)),
                ('package_checksum', models.CharField(max_length=64)),
                ('approval_history', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='quality.qualityreport')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='quality.qualitycycle')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_reports_generated', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tpmf_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_reports_tpmf_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('period', 'scope_type', 'scope_id', 'version'), name='quality_report_scope_period_version_unique')],
            },
        ),
    ]
