# Generated by Django 5.2.16 on 2026-07-19 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_accountsecurity_mfachallenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='source_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='source_public_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='source_status',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lecturer_id', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('expertise', models.TextField(blank=True)),
                ('expertise_tags', models.JSONField(blank=True, default=list)),
                ('identity_source', models.CharField(blank=True, max_length=32)),
                ('source_status', models.CharField(blank=True, max_length=24)),
                ('workload_summary', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['identity_source', 'source_status'], name='identity_le_identit_7520ad_idx')],
            },
        ),
    ]
