# Generated by Django 6.0.7 on 2026-07-19 04:47

import uuid

from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    EvidenceRecord = apps.get_model("evidence", "EvidenceRecord")
    for record in EvidenceRecord.objects.filter(public_id__isnull=True).iterator(chunk_size=500):
        record.public_id = uuid.uuid4()
        record.save(update_fields=["public_id"])


def clear_public_ids(apps, schema_editor):
    EvidenceRecord = apps.get_model("evidence", "EvidenceRecord")
    EvidenceRecord.objects.update(public_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('shared', '0002_remove_filemanifest_manifest_object_version_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='public_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_ids, reverse_code=clear_public_ids),
        migrations.AlterField(
            model_name='evidencerecord',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['object_type', 'object_id', 'status'], name='evidence_ev_object__1c3f3e_idx'),
        ),
    ]
