# Generated by Django 5.2.16 on 2026-07-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidencerecord_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='revision_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='source_status',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
