# Generated by Django 5.2.16 on 2026-07-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_evidencerecord_revision_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
