# Generated by Django 5.1.15 on 2026-07-25 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=20)),
                ('import_prodi', models.CharField(blank=True, max_length=64)),
                ('period', models.CharField(blank=True, max_length=32)),
                ('klass', models.CharField(blank=True, max_length=64)),
                ('timeline_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('batch_status', models.CharField(choices=[('Diunggah', 'Diunggah'), ('Divalidasi', 'Divalidasi'), ('Ditolak', 'Ditolak'), ('Dikomit', 'Dikomit'), ('Digagalkan', 'Digagalkan')], default='Diunggah', max_length=12)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=20)),
                ('is_implemented', models.BooleanField(default=False)),
                ('fields', models.JSONField(default=list)),
                ('reference_sources', models.JSONField(default=list)),
                ('validation_rules', models.JSONField(default=list)),
                ('business_key', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Definition',
                'verbose_name_plural': 'Template Definitions',
                'ordering': ['template_type', '-created_at'],
                'unique_together': {('template_type', 'schema_version')},
            },
        ),
        migrations.CreateModel(
            name='StagedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('raw_values', models.JSONField(default=dict)),
                ('business_key', models.CharField(db_index=True, max_length=255)),
                ('classification', models.CharField(blank=True, choices=[('New_Row', 'New Row'), ('Changed_Row', 'Changed Row'), ('Unchanged_Row', 'Unchanged Row'), ('Duplicate_Row', 'Duplicate Row'), ('Rejected_Row', 'Rejected Row')], max_length=16, null=True)),
                ('cell_errors', models.JSONField(default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='excel_import.importbatch')),
            ],
            options={
                'verbose_name': 'Staged Row',
                'verbose_name_plural': 'Staged Rows',
                'ordering': ['row_index'],
                'unique_together': {('batch', 'row_index')},
            },
        ),
    ]
