# Generated by Django 5.2.16 on 2026-07-19 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(choices=[('course-code', 'Course code'), ('course-offering', 'Course offering')], max_length=32)),
                ('legacy_identifier', models.CharField(max_length=120)),
                ('canonical_identifier', models.CharField(max_length=120)),
                ('status', models.CharField(default='resolved', max_length=24)),
                ('source_checksum', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['namespace', 'canonical_identifier'], name='integration_namespa_ce04a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('namespace', 'legacy_identifier'), name='identifier_alias_unique')],
            },
        ),
    ]
