# Generated by Django 5.2.16 on 2026-07-19 21:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_identifieralias'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('updated_by_actor_id', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(max_length=120, unique=True)),
                ('system', models.CharField(max_length=80)),
                ('direction', models.CharField(max_length=32)),
                ('mode', models.CharField(max_length=80)),
                ('schema_version', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=32)),
                ('write_feature_flag', models.CharField(blank=True, max_length=120)),
                ('source_snapshot', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='integration_integrationcontract_version_gte_1'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='integration_integrationcontract_effective_period_valid')],
            },
        ),
    ]
