# Generated by Django 6.0.7 on 2026-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_course_created_by_actor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='equivalence_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='curriculumedge',
            name='allocation_method',
            field=models.CharField(default='explicit', max_length=40),
        ),
        migrations.AddField(
            model_name='curriculumedge',
            name='approval_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='curriculumedge',
            name='is_unallocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='approval_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='approved_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='curriculum_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='degree_level',
            field=models.CharField(default='sarjana', max_length=40),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='program_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='reviewed_by_actor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='outcome',
            name='attitude_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='knowledge_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='owner_role',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='outcome',
            name='skill_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
