# Generated by Django 5.2.16 on 2026-07-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_course_equivalence_codes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curriculumversion',
            name='curriculum_program_version_unique',
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='source_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('program_code', 'cohort_from', 'version'), name='curriculum_program_cohort_version_unique'),
        ),
    ]
