# Generated by Django 5.2.16 on 2026-07-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_exam', '0002_exam_created_by_actor_id_exam_updated_by_actor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='source_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_status',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
