# Generated by Django 5.1.15 on 2026-07-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.CharField(blank=True, max_length=32)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpls', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'CPL',
                'verbose_name_plural': 'CPLs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseCPLContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_level', models.CharField(choices=[('Introduce', 'Introduce'), ('Reinforce', 'Reinforce'), ('Master', 'Master')], max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpl_contributions', to='curriculum.course')),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_contributions', to='curriculum.cpl')),
            ],
            options={
                'verbose_name': 'Course CPL Contribution',
                'verbose_name_plural': 'Course CPL Contributions',
                'constraints': [models.UniqueConstraint(fields=('course', 'cpl'), name='uniq_course_cpl_contribution')],
            },
        ),
        migrations.CreateModel(
            name='CPLIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=2, default=70.0, max_digits=6)),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='curriculum.cpl')),
            ],
            options={
                'verbose_name': 'CPL Indicator',
                'verbose_name_plural': 'CPL Indicators',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('cpl', 'code'), name='uniq_cplindicator_code_per_cpl')],
            },
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('prodi',), name='uniq_active_curriculum_per_prodi'),
        ),
        migrations.AddConstraint(
            model_name='cpl',
            constraint=models.UniqueConstraint(fields=('curriculum', 'code'), name='uniq_cpl_code_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('curriculum', 'code'), name='uniq_course_code_per_curriculum'),
        ),
    ]
