sops:
  age: []
  version: 3.10.2
database_password: ENC[AES256_GCM,data:REPLACE_WITH_SOPS,tag:REPLACE,type:str]
django_secret_key: ENC[AES256_GCM,data:REPLACE_WITH_SOPS,tag:REPLACE,type:str]
exam_signing_key: ENC[AES256_GCM,data:REPLACE_WITH_SOPS,tag:REPLACE,type:str]

