# Generated by Django 5.1.15 on 2026-07-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rps', '0001_rps_models'),
        ('timeline', '0002_seed_demo_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttainmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_ref', models.CharField(max_length=128)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gap', models.DecimalField(decimal_places=2, max_digits=6)),
                ('formula_name', models.CharField(max_length=128)),
                ('formula_version', models.PositiveIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attainment_results', to='timeline.obecycle')),
                ('source_scores', models.ManyToManyField(blank=True, related_name='attainment_results', to='rps.score')),
            ],
            options={
                'verbose_name': 'Attainment Result',
                'verbose_name_plural': 'Attainment Results',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CalculationFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('level', models.CharField(choices=[('criterion', 'Criterion'), ('indicator', 'Indicator'), ('subcpmk', 'Sub-CPMK'), ('cpmk', 'CPMK'), ('cpl', 'CPL')], max_length=16)),
                ('definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calculation Formula',
                'verbose_name_plural': 'Calculation Formulas',
                'ordering': ['name', '-version'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_formula_name_version')],
            },
        ),
    ]
