# Generated by Django 5.1.15 on 2026-07-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_demo_data'),
        ('curriculum', '0001_curriculum_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(blank=True, max_length=64)),
                ('period', models.CharField(blank=True, max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rps_plans', to='curriculum.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rps_plans', to='curriculum.curriculum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
            ],
            options={
                'verbose_name': 'RPS',
                'verbose_name_plural': 'RPS Plans',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('derived_from', models.ManyToManyField(blank=True, related_name='derived_cpmks', to='curriculum.cpl')),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmks', to='rps.rps')),
            ],
            options={
                'verbose_name': 'CPMK',
                'verbose_name_plural': 'CPMKs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='rps.rps')),
            ],
            options={
                'verbose_name': 'Assessment Instrument',
                'verbose_name_plural': 'Assessment Instruments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='rps.assessmentinstrument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demouser')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.programofstudy')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rps.rubric')),
            ],
            options={
                'verbose_name': 'Rubric Criterion',
                'verbose_name_plural': 'Rubric Criteria',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='rps.rubriccriterion')),
            ],
            options={
                'verbose_name': 'Rubric Level',
                'verbose_name_plural': 'Rubric Levels',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_proxy', models.CharField(blank=True, max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rps.rubriccriterion')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='SubCPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cpmks', to='rps.cpmk')),
            ],
            options={
                'verbose_name': 'Sub-CPMK',
                'verbose_name_plural': 'Sub-CPMKs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubCPMKIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('sub_cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='rps.subcpmk')),
            ],
            options={
                'verbose_name': 'Sub-CPMK Indicator',
                'verbose_name_plural': 'Sub-CPMK Indicators',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='mapped_indicators',
            field=models.ManyToManyField(blank=True, related_name='mapped_criteria', to='rps.subcpmkindicator'),
        ),
    ]
